name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Debug before checkout
        run: |
          echo "Current directory before checkout:"
          pwd
          ls -la

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: frontend

      - name: Debug after checkout
        run: |
          echo "Current directory after checkout:"
          pwd
          echo "Repository contents:"
          cd frontend
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run unit tests
        working-directory: ./frontend
        run: npm run test:unit